export const dayStart = 9 * 60;
export const dayEnd = 21 * 60;
export const tickMs = 100;
export const realSecondsPerDay = 40;
export const tickMinutes = ((dayEnd - dayStart) * tickMs) / (realSecondsPerDay * 1000);
export const currencyName = "鸭币";
export const survivalDays = 15;

export const whaleGooseGroup = "白鲸大学西门鹅腿群34";
export const whaleDuckGroup = "白鲸大学西门鸭腿群34";
export const frogGooseGroup = "青蛙大学东门鹅腿群35";
export const frogDuckGroup = "青蛙大学东门鸭腿群35";
export const uncleGroupNick = "鸭腿叔叔-排队中请留言";
export const defaultHomeSchoolName = "白鲸大学";
export const universityMarketKeys = ["frog", "deer", "lion"];

export const initialState = {
  dayIndex: 0,
  calendarDay: 1,
  activeTask: 0,
  minute: dayStart,
  started: false,
  speed: 1,
  autoPausedForPending: false,
  tickCarry: 0,
  cash: 120,
  dayStartCash: 120,
  reputation: 58,
  conscience: 72,
  risk: 12,
  heat: 36,
  family: 22,
  documents: 56,
  margin: 46,
  cost: 28,
  dailyExpense: 22,
  honestDays: 0,
  activeMainTab: "chat",
  homeSchoolName: defaultHomeSchoolName,
  selectedUniversityMarkets: [],
  price: 22,
  policy: "balanced",
  source: "freshDuck",
  productFocus: "duck",
  staff: 1,
  paidTraffic: 0,
  markets: {
    whale: true,
    frog: false,
    deer: false,
    lion: false,
    cbd: false,
  },
  marketContacts: {
    whale: "ready",
    frog: "locked",
    deer: "locked",
    lion: "locked",
    cbd: "locked",
  },
  marketRequestDue: {},
  manualCampusRequests: {},
  suspendedUntilDay: 0,
  suspensionReason: "",
  marketSuspensions: {},
  dailyIncidentKeys: {},
  dailyStoryKeys: {},
  effectQueue: [],
  routes: {
    compliance: 0,
    contraction: 0,
    hype: 0,
    pr: 0,
    evasion: 0,
    restart: 0,
    goodwill: 0,
  },
  flags: {
    clearLabel: false,
    shadyStock: false,
    invoice: false,
    apology: false,
    prAgency: false,
    studentRefund: false,
  },
  completed: {},
  replies: {},
  requests: {},
  chatHistory: {},
  knownChats: {},
  chatOrder: [],
  activeChatTitle: "",
  injectedMessages: {},
  overdueHits: {},
  dayCostsCharged: {},
  seenFeatureUnlocks: {},
  tickerText: "",
  tickerUntil: 0,
  history: [],
  dayReports: [],
  seenTasks: {},
  log: [],
  ended: false,
};

export const metricDetails = {
  profitDetails: [
    ["毛利空间", "margin"],
    ["成本", "cost"],
    ["日常花销", "dailyExpense"],
  ],
  riskDetails: [
    ["票据缺口", "documents", true],
    ["监管压力", "risk"],
    ["良心亏空", "conscience", true],
  ],
  trafficDetails: [
    ["群聊热度", "heat"],
    ["口碑", "reputation"],
    ["未读压力", "family"],
  ],
};

export const routeDetails = {
  compliance: ["合规小摊线", "把商品名、原料、票据、核销和检测尽量做成闭环。"],
  contraction: ["收缩保摊线", "主动限量、砍单、暂停扩张，用规模换确定性。"],
  hype: ["黑红流量线", "用低价、免费、直播和冲量维持热度，让问题继续滚动。"],
  pr: ["公关叙事线", "把食品和经营问题包装成故事、通稿和人设维护。"],
  evasion: ["拖延回避线", "用小字、撤回、拒绝回应或甩锅来争取时间。"],
  restart: ["换壳重启线", "把旧摊、旧账号或旧责任留在身后，换地方继续卖故事。"],
  goodwill: ["补偿修复线", "用退款、补券、道歉和公开账本换回部分信任。"],
};

export const routeRules = [
  ["compliance", 2, /鹅腿|原料|票据|核销|送检|明示|写清|停售|退款|道歉|公开账本|冷链|配合检查|完整票据/],
  ["contraction", 1, /限量|少卖|慢慢扩|先不|拒绝|砍掉|减量|收缩|暂停|停售|短租|试营业|保住交付/],
  ["hype", 2, /冲量|免费领|直播|硬刚|低价|老价格|都免费|好评|诱导|领券下单|挂名|热度爆炸/],
  ["pr", 2, /公关|通稿|创业不易|人设|故事|控评|营销|脚本|小本生意/],
  ["evasion", 2, /别提|别问|不写清|小字|备注|撤回|不回应|推给供应商|压住|暂时不接受|先别|绕开|含糊|灰色/],
  ["restart", 2, /换个城市|重新开号|新号|授权|挂名|另一个|复制旧/],
  ["goodwill", 1, /补券|免单|退款|道歉|公开账本|补偿|登记/],
];

export const policyOptions = {
  transparent: {
    label: "明示稳摊",
    desc: "写清原料、限量接单，流量慢一些，风险涨得慢。",
    demandMultiplier: 0.86,
    capacityPerDay: 72,
    operatingCost: 2,
    clarity: 0.92,
    promoExposure: 0.76,
    paperworkDiscipline: 0.9,
    goodwill: 0.55,
  },
  balanced: {
    label: "正常经营",
    desc: "维持普通团购节奏，收益和风险都按当前规模累积。",
    demandMultiplier: 1,
    capacityPerDay: 95,
    operatingCost: 1.4,
    clarity: 0.62,
    promoExposure: 1,
    paperworkDiscipline: 0.55,
    goodwill: 0,
  },
  hype: {
    label: "冲量营销",
    desc: "多发券、多吆喝，订单和热度更快，舆论与履约风险也更快。",
    demandMultiplier: 1.28,
    capacityPerDay: 126,
    operatingCost: 2.4,
    clarity: 0.34,
    promoExposure: 1.45,
    paperworkDiscipline: 0.28,
    goodwill: -0.3,
  },
};

export const sourceOptions = {
  goose: {
    label: "主卖鹅腿",
    desc: "真鹅腿成本高、供应少、冷链贵，适合限量稳卖，很难靠它赚大钱。",
    unitCost: 31,
    referencePrice: 39,
    priceElasticity: 2.25,
    supplyReliability: 0.58,
    fixedCost: 470,
    extraMarketCost: 42,
    foodRisk: 0.08,
    labelRisk: 0.03,
    documentFit: 0.92,
    conscience: 0.72,
  },
  freshDuck: {
    label: "主卖鸭腿",
    desc: "稳定、成本中等，只要明示清楚就适合长期经营。",
    unitCost: 14,
    referencePrice: 22,
    priceElasticity: 1.2,
    supplyReliability: 1,
    foodRisk: 0.16,
    labelRisk: 0.3,
    documentFit: 0.66,
    conscience: 0.5,
  },
  frozenDuck: {
    label: "低价鸭边腿",
    desc: "便宜、利润厚，但批次和食品疑点会持续积累。",
    unitCost: 8,
    referencePrice: 18,
    priceElasticity: 0.95,
    supplyReliability: 1.16,
    foodRisk: 0.66,
    labelRisk: 0.56,
    documentFit: 0.18,
    conscience: 0.12,
  },
};

export const marketOptions = {
  whale: {
    label: "白鲸大学",
    desc: "起步市场，订单稳定，舆论扩散速度可控。",
    unlockCost: 0,
    contactCost: 0,
    requiredStaff: 1,
    requiredTraffic: 0,
    dailyDemand: 48,
    exposure: 0.75,
    regulation: 0.35,
  },
  frog: {
    label: "青蛙大学",
    desc: "跨校配送，订单增加，截图和迟到投诉更多。",
    unlockCost: 80,
    contactCost: 20,
    requiredStaff: 2,
    requiredTraffic: 40,
    dailyDemand: 72,
    exposure: 1,
    regulation: 0.5,
  },
  deer: {
    label: "鹿大",
    desc: "社团活动多，团单机会高，但配送时段集中。",
    unlockCost: 90,
    contactCost: 24,
    requiredStaff: 2,
    requiredTraffic: 42,
    dailyDemand: 76,
    exposure: 1.05,
    regulation: 0.48,
  },
  lion: {
    label: "白狮大学",
    desc: "校内号传播快，客单更高，也更容易被公开对比。",
    unlockCost: 110,
    contactCost: 28,
    requiredStaff: 2,
    requiredTraffic: 46,
    dailyDemand: 82,
    exposure: 1.18,
    regulation: 0.58,
  },
  cbd: {
    label: "果猫商业区",
    desc: "客单和曝光都高，合同、供货和监管要求更硬。",
    unlockCost: 180,
    contactCost: 50,
    requiredStaff: 3,
    requiredTraffic: 62,
    dailyDemand: 96,
    exposure: 1.35,
    regulation: 0.86,
  },
};

export const operatingModel = {
  minutesPerDay: dayEnd - dayStart,
  baseComplianceNeed: 0.48,
  challengeStartDay: 6,
  lateChallengeDay: 9,
  challengeCostPerDay: 3,
  lateChallengeCostPerDay: 10,
  challengeCompliancePerDay: 0.01,
  lateChallengeCompliancePerDay: 0.03,
  challengeRiskPerDay: 0.04,
  lateChallengeRiskPerDay: 0.22,
  overloadRiskWeight: 4.6,
  foodRiskWeight: 3.5,
  labelRiskWeight: 3,
  regulationRiskWeight: 2.1,
  heatFromDemand: 0.48,
  heatFromControversy: 0.72,
  suspensionWageRate: 0.35,
  staffCapacityPerDay: 58,
  staffDailyWage: 115,
  staffHiringCost: 45,
  baseLogisticsCost: 24,
  extraMarketLogisticsCost: 45,
  extraStaffManagementCost: 32,
  scaleComplianceWeight: 0.14,
  riskDemandPenaltyStart: 58,
  riskDemandPenaltyRate: 0.007,
  reputationCost: 60,
  trafficCost: 70,
  trafficBoost: 32,
};
